import type { PortfolioContent } from './types'

/**
 * Fallback content, mirroring supabase/schema.sql's seed block.
 *
 * Used when Supabase is not configured, or when a fetch fails — the site
 * always renders something real rather than an empty shell. Once you edit
 * anything in /admin, Supabase becomes the source of truth and this is only
 * ever a safety net.
 */
export const seedContent: PortfolioContent = {
  settings: {
    id: 1,
    name: 'Delson James Tubiera',
    role: 'Software Developer II',
    tagline: 'Full Stack · .NET / Blazor',
    hero_intro:
      'I build and maintain enterprise .NET systems for banking — payment platforms, core-banking API integrations, and the automation tooling that keeps them shippable.',
    about:
      "I'm a full stack developer based in Makati City, currently building Biller Plus, the enterprise bills payment platform at Rizal Commercial Banking Corporation. My work sits where reliability actually matters: payment posting through Finacle core banking, rate limiting and reverse proxying to keep APIs standing up under load, and production monitoring when something goes wrong at 2am.\n\nBefore banking I spent time in GIS web services, billing systems, and financial services production support — the kind of work that teaches you to care about query plans and error logs. I also enjoy building tools for the people around me: most recently a low-code automation testing platform that let QA engineers with no coding background write and run their own test suites.",
    location: 'Makati City, Metro Manila',
    email: 'delsonjames17@gmail.com',
    phone: '+63 908 930 9958',
    available: true,
    available_note: 'Open to senior full stack and backend roles',
    avatar_url: null,
    resume_url: null,
    socials: [
      { label: 'GitHub', url: 'https://github.com/Delson-James17' },
      {
        label: 'LinkedIn',
        url: 'https://www.linkedin.com/in/delson-james-tubiera/',
      },
      { label: 'Email', url: 'mailto:delsonjames17@gmail.com' },
    ],
    metrics: [
      { value: '5+', label: 'Years building for the web' },
      { value: '110x', label: 'Faster billing file processing' },
      { value: '4', label: 'Enterprise clients shipped for' },
    ],
    seo_title: 'Delson James Tubiera — Full Stack .NET Developer',
    seo_description:
      'Software Developer II specialising in .NET 8, Blazor, and ASP.NET Core. Building enterprise banking and payment platforms in Metro Manila.',
    hero_layout: 'editorial',
    hero_image_url: null,
    theme_preset: 'obsidian',
    accent_color: '#e9a94b',
    font_pair: 'inter',
    work_layout: 'list',
    skills_layout: 'grouped',
    experience_layout: 'rows',
    about_layout: 'sidebar',
    certs_layout: 'grid',
    contact_layout: 'split',
  },

  palettes: [],

  projects: [
    {
      id: 'seed-1',
      slug: 'biller-plus',
      title: 'Biller Plus',
      blurb:
        "RCBC's enterprise bills payment platform — .NET 8, Blazor, and Finacle core banking integration.",
      description:
        "Biller Plus is Rizal Commercial Banking Corporation's enterprise bills payment platform. I develop and maintain the system end to end: an ASP.NET Core Web API backend on .NET 8, a Blazor front end, and Microsoft SQL Server for persistence.\n\nThe interesting problems here are integration and resilience. Payment posting and account services run through Finacle scripting against the bank's core system, so correctness is non-negotiable. On the edge, I implemented rate limiting, load balancing, and a reverse proxy layer to hold API throughput and availability up under abusive traffic.",
      role: 'Software Developer II',
      year: '2025 — Present',
      tech: [
        '.NET 8',
        'ASP.NET Core Web API',
        'Blazor',
        'SQL Server',
        'Finacle Scripting',
      ],
      highlights: [
        "Integrated payment posting and account services with the bank's Finacle core",
        'Added rate limiting, load balancing and a reverse proxy to protect API throughput',
        'Maintain production monitoring and incident response for a live banking platform',
      ],
      repo_url: null,
      live_url: null,
      cover_url: null,
      featured: true,
      published: true,
      sort_order: 1,
    },
    {
      id: 'seed-2',
      slug: 'qa-automation-platform',
      title: 'Low-Code QA Automation Platform',
      blurb:
        'A test authoring platform that let QA engineers with zero coding background build and run automated suites.',
      description:
        'The team was fully dependent on manual regression testing. I designed and built a low-code automation testing platform on Playwright, Appium, and Electron that lets QA engineers author and execute automated tests without writing code.\n\nIt handles single and bulk API testing, web UI testing, and mobile testing from one interface. It runs from a CLI and generates its own CI/CD assets — Dockerfiles plus AWS and Azure YAML pipeline configs. It also performs security scanning for CSRF, brute-force, and SQL injection vulnerabilities, and auto-generates both executable test scripts and test case documentation from whatever the user builds.',
      role: 'Designer & Lead Developer',
      year: '2025',
      tech: ['Playwright', 'Appium', 'Electron', 'Docker', 'AWS', 'Azure', 'CI/CD'],
      highlights: [
        "Removed the team's dependency on manual regression testing",
        'One interface for API, web UI, and mobile test authoring',
        'Generates Dockerfiles and AWS/Azure YAML pipeline configuration',
        'Security scanning for CSRF, brute-force and SQL injection',
        'Auto-generates executable scripts and test case documentation',
      ],
      repo_url: null,
      live_url: null,
      cover_url: null,
      featured: true,
      published: true,
      sort_order: 2,
    },
    {
      id: 'seed-3',
      slug: 'billing-system',
      title: 'Billing System — 110x Faster',
      blurb:
        'Cut Excel processing in a production billing module from 15 seconds to 0.135 seconds.',
      description:
        "Built and maintained a billing system on ASP.NET Core MVC with Microsoft SQL Server, implementing the business logic and the integration layer.\n\nThe result I'm most pleased with is a performance one. The module's Excel file processing took 15 seconds per run. After reworking how the data was read and processed, the same job finished in 0.135 seconds — a 99.10% reduction, and a 110x speed increase.",
      role: 'Full Stack Developer',
      year: '2024 — 2025',
      tech: ['ASP.NET Core MVC', 'C#', 'SQL Server', 'Entity Framework'],
      highlights: [
        '15s → 0.135s Excel processing: 99.10% reduction, 110x faster',
        'Designed the database architecture for scalability and maintainability',
        'Built internal C# and JavaScript libraries that cut recurring bugs across projects',
      ],
      repo_url: null,
      live_url: null,
      cover_url: null,
      featured: true,
      published: true,
      sort_order: 3,
    },
    {
      id: 'seed-4',
      slug: 'gis-web-services',
      title: 'GIS Web Services Platform',
      blurb:
        'Scalable ASP.NET Web API and WCF services backing GIS applications on Oracle.',
      description:
        "Developed and integrated scalable web services using ASP.NET Web API and WCF for GIS applications, streamlining data management against an Oracle database.\n\nI also led the planning and design of the database architecture across company projects, with a focus on scalability, efficiency, and long-term maintainability — and helped establish the team's programming practices for keeping the codebase clean and consistent.",
      role: 'Full Stack Developer',
      year: '2024 — 2025',
      tech: ['ASP.NET Web API', 'WCF', 'Oracle', 'PL/SQL', 'OpenLayers'],
      highlights: [
        'Led database architecture planning across company projects',
        'Streamlined GIS data management on Oracle',
        'Established team-wide programming standards and review practices',
      ],
      repo_url: null,
      live_url: null,
      cover_url: null,
      featured: false,
      published: true,
      sort_order: 4,
    },
    {
      id: 'seed-5',
      slug: 'pjli-core-platform',
      title: 'Financial Services Core Platform',
      blurb:
        "Feature work, internal APIs, and production support for PJ Lhuillier's core web platform.",
      description:
        "Developed features and resolved defects on the core web platform of a major financial services provider, and built the internal APIs consumed by the organisation's main web service.\n\nA large part of this role was production support — investigating live errors, performing data fixes, and shipping bug fixes under tight turnaround windows. I also wrote SQL scripts and stored procedures to optimise database operations and extend system functionality.",
      role: 'Software Engineer',
      year: '2023 — 2024',
      tech: ['C#', 'ASP.NET MVC', 'REST API', 'SQL Server', 'Jira'],
      highlights: [
        'Top Performer Awardee, PJ Lhuillier Group of Companies (Jan 2024)',
        "Built internal APIs consumed by the organisation's main web service",
        'Production support: live error investigation, data fixes, tight-turnaround releases',
      ],
      repo_url: null,
      live_url: null,
      cover_url: null,
      featured: false,
      published: true,
      sort_order: 5,
    },
  ],

  experiences: [
    {
      id: 'seed-e1',
      company: 'Vertere Global Solutions, Inc.',
      client: 'Rizal Commercial Banking Corporation (RCBC)',
      role: 'Software Developer II',
      period: 'Sep 2025 — Present',
      location: 'Makati City',
      summary:
        "Building and maintaining RCBC's enterprise bills payment platform, plus the automation tooling around it.",
      bullets: [
        "Develop and maintain Biller Plus, RCBC's enterprise bills payment platform on .NET 8, ASP.NET Core Web API, Blazor and SQL Server",
        'Build and consume core banking APIs through Finacle scripting for payment posting and account services',
        'Implemented rate limiting, load balancing and a reverse proxy layer to strengthen API throughput and availability',
        'Maintain and monitor production applications, including in-app chat enhancements and incident monitoring',
        'Designed and built a low-code automation testing platform (Playwright, Appium, Electron) for non-coding QA engineers',
      ],
      tech: ['.NET 8', 'Blazor', 'ASP.NET Core', 'SQL Server', 'Finacle', 'Playwright'],
      published: true,
      sort_order: 1,
    },
    {
      id: 'seed-e2',
      company: 'Pacific Data Resources (Asia), Inc.',
      client: '',
      role: 'Software Developer I — Full Stack',
      period: 'Sep 2024 — Sep 2025',
      location: 'Metro Manila',
      summary:
        'GIS web services, billing systems, and the database architecture behind them.',
      bullets: [
        'Developed scalable web services using ASP.NET Web API and WCF for GIS applications on Oracle',
        'Led planning and design of database architecture across company projects',
        'Built the Billing System on ASP.NET Core MVC with complex business logic and SQL Server integration',
        'Cut Excel file processing from 15s to 0.135s — a 99.10% reduction and 110x speed increase',
        'Created internal C# and JavaScript libraries that reduced recurring bugs across projects',
        'Established best programming practices for clean, readable, consistent code',
      ],
      tech: ['ASP.NET Core MVC', 'WCF', 'Oracle', 'SQL Server', 'jQuery', 'Bootstrap'],
      published: true,
      sort_order: 2,
    },
    {
      id: 'seed-e3',
      company: 'Collabera Digital',
      client: 'PJ Lhuillier, Inc. (PJLI)',
      role: 'Software Engineer — Full Stack',
      period: 'Feb 2023 — Jul 2024',
      location: 'Metro Manila',
      summary:
        'Feature delivery and production support on a financial services core web platform.',
      bullets: [
        "Developed features and resolved defects for a financial services provider's core web platform",
        "Built internal APIs consumed by the organisation's main web service",
        'Handled production support: error investigation, data fixes, and bug fixes under tight turnaround',
        'Developed SQL scripts and stored procedures to optimise database operations',
        'Tracked and organised delivery work using Jira boards',
      ],
      tech: ['C#', 'ASP.NET MVC', 'REST API', 'SQL Server', 'SSMS', 'Jira'],
      published: true,
      sort_order: 3,
    },
    {
      id: 'seed-e4',
      company: 'Tilden Tasks LLC dba WP Tangerine',
      client: '',
      role: 'Website Developer',
      period: 'Jan 2020 — Feb 2023',
      location: 'Berkeley, California (Remote)',
      summary: 'E-commerce and client web work across .NET, WordPress and Shopify.',
      bullets: [
        'Developed an e-commerce project using C# and ASP.NET Core',
        'Built and customised WordPress and Shopify sites with e-commerce solutions',
        'Applied HTML, CSS, JavaScript, C# and responsive design across client sites',
      ],
      tech: ['C#', 'ASP.NET Core', 'WordPress', 'Shopify', 'JavaScript'],
      published: true,
      sort_order: 4,
    },
  ],

  skills: [
    {
      id: 'seed-s1',
      label: 'Back-End',
      items: [
        'C#',
        '.NET 8',
        '.NET Core',
        'ASP.NET Core Web API',
        'ASP.NET Core MVC',
        'Entity Framework',
        'LINQ',
        'ADO.NET',
        'WCF',
        'REST API',
        'SOAP API',
        'Finacle Scripting',
      ],
      sort_order: 1,
    },
    {
      id: 'seed-s2',
      label: 'Front-End',
      items: [
        'Blazor (WASM / Server)',
        'React.js',
        'TypeScript',
        'JavaScript',
        'HTML',
        'CSS',
        'jQuery',
        'SyncFusion',
        'Bootstrap',
      ],
      sort_order: 2,
    },
    {
      id: 'seed-s3',
      label: 'Database',
      items: [
        'Microsoft SQL Server',
        'Oracle',
        'PL/SQL',
        'MySQL',
        'Stored Procedures',
        'Query Optimization',
        'Supabase',
        'Firebase',
      ],
      sort_order: 3,
    },
    {
      id: 'seed-s4',
      label: 'Architecture & Security',
      items: [
        'Rate Limiting',
        'Load Balancing',
        'Reverse Proxy',
        'API Gateway',
        'CSRF Mitigation',
        'SQL Injection Mitigation',
        'Brute-Force Mitigation',
        'Application Monitoring',
      ],
      sort_order: 4,
    },
    {
      id: 'seed-s5',
      label: 'Testing & Automation',
      items: [
        'Playwright',
        'Appium',
        'Electron',
        'API & UI Automation',
        'Mobile Test Automation',
        'Postman',
        'SoapUI',
        'Test Documentation',
      ],
      sort_order: 5,
    },
    {
      id: 'seed-s6',
      label: 'DevOps & Cloud',
      items: [
        'Docker',
        'Kubernetes',
        'CI/CD Pipelines',
        'AWS',
        'Azure',
        'YAML Pipelines',
        'IIS',
        'Netlify',
        'Vercel',
      ],
      sort_order: 6,
    },
    {
      id: 'seed-s7',
      label: 'Tools',
      items: [
        'Git',
        'GitHub',
        'GitLab',
        'Visual Studio',
        'VS Code',
        'Jira',
        'SharePoint',
        'Notion',
        'WordPress',
        'Shopify',
      ],
      sort_order: 7,
    },
  ],

  certifications: [
    {
      id: 'seed-c1',
      title: 'Top Performer Awardee',
      issuer: 'PJ Lhuillier Group of Companies',
      date_label: 'January 2024',
      url: null,
      sort_order: 1,
    },
    {
      id: 'seed-c2',
      title: 'Amazing .NET Developer Training Award, Weeks 1–4',
      issuer: 'Collabera Digital',
      date_label: 'March 2023',
      url: null,
      sort_order: 2,
    },
    {
      id: 'seed-c3',
      title: 'Certificate of Completion: .NET Full Stack',
      issuer: 'Collabera Digital',
      date_label: 'May 2023',
      url: null,
      sort_order: 3,
    },
    {
      id: 'seed-c4',
      title: 'Responsive Web Design Certification',
      issuer: 'freeCodeCamp',
      date_label: 'October 2022',
      url: null,
      sort_order: 4,
    },
  ],
}
