import type { PortfolioContent } from './types'

/** Empty fallback content used when Supabase is not configured or unavailable. */
export const seedContent: PortfolioContent = {
  settings: {
    id: 1,
    name: '',
    role: '',
    tagline: '',
    hero_intro: '',
    about: '',
    location: '',
    email: '',
    phone: '',
    available: false,
    available_note: '',
    avatar_url: null,
    resume_url: null,
    socials: [],
    metrics: [],
    seo_title: '',
    seo_description: '',
    og_image_url: null,
    logo_url: null,
    favicon_url: null,
    logo_text: '',
    logo_mark: 'dot',
    favicon_bg_color: '#e9a94b',
    favicon_text_color: '#12100b',
    favicon_match_nav: true,
    hero_layout: 'editorial',
    hero_image_url: null,
    theme_preset: 'obsidian',
    accent_color: '#e9a94b',
    font_pair: 'inter',
    work_layout: 'list',
    work_limit: 6,
    skills_layout: 'grouped',
    experience_layout: 'rows',
    about_layout: 'sidebar',
    certs_layout: 'grid',
    contact_layout: 'split',
    background_effect: 'none',
    effect_intensity: 'subtle',
    effect_rotation: 'off',
    rotation_pool: [],
  },
  projects: [],
  experiences: [],
  skills: [],
  certifications: [],
  palettes: [],
  schedules: [],
}